### ISSUE TITLE
TODO: Make a Full Featured Gateway

### ISSUE THREAD

**Issue by Helloyunho** [harmony-org/harmony#11]
## Gateway Commands

- [x] Identify
- [x] Resume
- [x] Heartbeat
- [x] Request Guild Members
- [x] Update Voice State
- [x] Update Status

## Gateway Event Handlers

- [x] Hello
- [x] Ready
- [x] Resumed
- [x] Reconnect
- [x] Invalid Session
- [x] Channel Create
- [x] Channel Update
- [x] Channel Delete
- [x] Channel Pins Update
- [x] Guild Create
- [x] Guild Update
- [x] Guild Delete
- [x] Guild Ban Add
- [x] Guild Ban Remove
- [x] Guild Emojis Update
- [x] Guild Integrations Update
- [x] Guild Member Add
- [x] Guild Member Remove
- [x] Guild Member Update
- [x] Guild Members Chunk
- [x] Guild Role Create
- [x] Guild Role Update
- [x] Guild Role Delete
- [x] Invite Create
- [x] Invite Delete
- [x] Message Create
- [x] Message Update
- [x] Message Delete
- [x] Message Delete Bulk
- [x] Message Reaction Add
- [x] Message Reaction Remove
- [x] Message Reaction Remove All
- [x] Message Reaction Remove Emoji
- [x] Presence Update
- [x] Typing Start
- [x] User Update
- [x] Voice State Update
- [x] Voice Server Update
- [x] Webhooks Update

**Comment by DjDeveloperr** [comment]
This needs to be updated as of https://github.com/harmony-org/harmony/pull/36

**Comment by Helloyunho** [comment]
![image](https://user-images.githubusercontent.com/10192625/100866372-e5a1cb00-34db-11eb-82f9-548362d3dae7.png)

**Comment by DjDeveloperr** [comment]
Update Voice State is left - it would be added with upcoming voice support.
At the moment, REST-related methods for structures and managers are a priority.

**Comment by DjDeveloperr** [comment]
`Gateway#updateVoiceState` and `VoiceChannel` methods like `join` and `leave` are here, marking this as complete!
